/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tenants/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    name?: string;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantsResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantsResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantsResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/{tenantId}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tenants/{tenantId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query: {
                    active: boolean;
                };
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.RoleOutput"][];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.RoleOutput"][];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.RoleOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    name?: string;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UsersResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UsersResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UsersResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.CreateUserRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.CreateUserRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.CreateUserRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/tenantId={tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"][];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"][];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query: {
                    active: boolean;
                };
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/revoke-refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.RevokeTokenRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.RevokeTokenRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.RevokeTokenRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/profile/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/profile/{tenantId}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantContactsResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tenants/profile/{tenantId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query: {
                    active: boolean;
                };
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tenants/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.RoleOutput"][];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.RoleOutput"][];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.RoleOutput"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/users/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    name?: string;
                    sort?: string;
                };
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UsersResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UsersResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UsersResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.CreateUserRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.CreateUserRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.CreateUserRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants/users/{tenantId}/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tenantId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query: {
                    active: boolean;
                };
                header?: never;
                path: {
                    tenantId: number;
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/identity/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.SignupRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.SignupRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.SignupRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.VerifyEmailRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.VerifyEmailRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.VerifyEmailRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/resend-verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    email?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.SigninRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.SigninRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.SigninRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.SigninResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.SigninResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.SigninResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.SigninResponse"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.SigninResponse"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.SigninResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.ForgotPasswordRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.ForgotPasswordRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.ResetPasswordRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.ResetPasswordRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.EditUserRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AP.Identity.Internal.Models.ChangePasswordRequest"];
                    "text/json": components["schemas"]["AP.Identity.Internal.Models.ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["AP.Identity.Internal.Models.ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query: {
                    active: boolean;
                };
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "application/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                        "text/json": components["schemas"]["AP.Identity.Internal.Models.UserOutput"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "AP.Common.Models.TenantRole": {
            /** Format: int32 */
            tenantId?: number | null;
            /** Format: int32 */
            roleId?: number | null;
            roleName?: string | null;
        };
        "AP.Identity.Internal.Models.ChangePasswordRequest": {
            /** Format: int32 */
            userId: number;
            /** Format: email */
            email: string;
            currentPassword: string;
            newPassword: string;
        };
        "AP.Identity.Internal.Models.CreateUserRequest": {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            /** Format: tel */
            phone?: string | null;
            /** Format: int32 */
            roleId: number;
            /** Format: int32 */
            tenantId: number;
        };
        "AP.Identity.Internal.Models.EditUserRequest": {
            /** Format: int32 */
            userId: number;
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            /** Format: tel */
            phone?: string | null;
            /** Format: int32 */
            roleId: number;
        };
        "AP.Identity.Internal.Models.ForgotPasswordRequest": {
            /** Format: email */
            email: string;
        };
        "AP.Identity.Internal.Models.ResetPasswordRequest": {
            resetToken: string;
            /** Format: email */
            email: string;
            password: string;
            confirmPassword: string;
        };
        "AP.Identity.Internal.Models.RevokeTokenRequest": {
            refreshToken: string;
            /** Format: email */
            email: string;
        };
        "AP.Identity.Internal.Models.RoleOutput": {
            /** Format: int32 */
            roleId?: number;
            roleName?: string | null;
            roleDescription?: string | null;
        };
        "AP.Identity.Internal.Models.SigninRequest": {
            /** Format: email */
            email: string;
            password: string;
        };
        "AP.Identity.Internal.Models.SigninResponse": {
            /** Format: int32 */
            userId?: number;
            firstName?: string | null;
            lastName?: string | null;
            email?: string | null;
            phone?: string | null;
            /** Format: int32 */
            roleId?: number;
            roleName?: string | null;
            active?: boolean;
            isVerified?: boolean;
            /** Format: date-time */
            created?: string;
            readonly fullName?: string | null;
        };
        "AP.Identity.Internal.Models.SignupRequest": {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
        };
        "AP.Identity.Internal.Models.Tenants.ContactInput": {
            /** Format: int32 */
            contactId?: number | null;
            contactName?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: tel */
            phone?: string | null;
            title?: string | null;
            address?: string | null;
            active?: boolean;
            primary?: boolean;
        };
        "AP.Identity.Internal.Models.Tenants.ContactOutput": {
            /** Format: int32 */
            contactId?: number;
            contactName?: string | null;
            email?: string | null;
            phone?: string | null;
            title?: string | null;
            address?: string | null;
            active?: boolean;
            primary?: boolean;
            /** Format: date-time */
            createdOn?: string;
        };
        "AP.Identity.Internal.Models.Tenants.TenantContactsRequest": {
            contacts?: components["schemas"]["AP.Identity.Internal.Models.Tenants.ContactInput"][] | null;
        };
        "AP.Identity.Internal.Models.Tenants.TenantContactsResponse": {
            /** Format: int32 */
            tenantId?: number;
            contacts?: components["schemas"]["AP.Identity.Internal.Models.Tenants.ContactOutput"][] | null;
        };
        "AP.Identity.Internal.Models.Tenants.TenantOutput": {
            /** Format: int32 */
            tenantId?: number;
            tenantName?: string | null;
            tenantBIC?: string | null;
            /** Format: int32 */
            tenantType?: number;
            /** Format: int32 */
            ownership?: number;
            domain?: string | null;
            summary?: string | null;
            logoUrl?: string | null;
            active?: boolean;
            enabled?: boolean;
            /** Format: date-time */
            createdOn?: string;
            /** Format: int32 */
            createdBy?: number | null;
            /** Format: date-time */
            updatedOn?: string | null;
            /** Format: int32 */
            updatedBy?: number | null;
            contacts?: components["schemas"]["AP.Identity.Internal.Models.Tenants.ContactOutput"][] | null;
        };
        "AP.Identity.Internal.Models.Tenants.TenantRequest": {
            tenantName: string;
            tenantBIC?: string | null;
            /** Format: int32 */
            tenantType: number;
            /** Format: int32 */
            ownership: number;
            optionalFields?: components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantRequestOptionalFields"];
            contacts?: components["schemas"]["AP.Identity.Internal.Models.Tenants.ContactInput"][] | null;
        };
        "AP.Identity.Internal.Models.Tenants.TenantRequestOptionalFields": {
            domain?: string | null;
            summary?: string | null;
            logoUrl?: string | null;
        };
        "AP.Identity.Internal.Models.Tenants.TenantsResponse": {
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            page?: number | null;
            /** Format: int32 */
            size?: number | null;
            name?: string | null;
            sort?: string | null;
            tenants?: components["schemas"]["AP.Identity.Internal.Models.Tenants.TenantOutput"][] | null;
        };
        "AP.Identity.Internal.Models.UserOutput": {
            /** Format: int32 */
            userId?: number;
            firstName?: string | null;
            lastName?: string | null;
            email?: string | null;
            phone?: string | null;
            tenantRoles?: components["schemas"]["AP.Common.Models.TenantRole"][] | null;
            active?: boolean | null;
            isVerified?: boolean;
            /** Format: date-time */
            createdOn?: string;
        };
        "AP.Identity.Internal.Models.UsersResponse": {
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            page?: number | null;
            /** Format: int32 */
            size?: number | null;
            name?: string | null;
            /** Format: int32 */
            role?: number | null;
            sort?: string | null;
            users?: components["schemas"]["AP.Identity.Internal.Models.UserOutput"][] | null;
        };
        "AP.Identity.Internal.Models.VerifyEmailRequest": {
            verificationToken: string;
            /** Format: email */
            email: string;
            password: string;
            confirmPassword: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
